
-- Primary Keys y Auto Increment
ALTER TABLE Facultad MODIFY ID_Facultad INT AUTO_INCREMENT PRIMARY KEY;
ALTER TABLE Departamento MODIFY ID_Departamento INT AUTO_INCREMENT PRIMARY KEY;
ALTER TABLE Programa_Academico MODIFY ID_Programa INT AUTO_INCREMENT PRIMARY KEY;
ALTER TABLE Usuario MODIFY ID_Usuario INT AUTO_INCREMENT PRIMARY KEY;
ALTER TABLE Rol MODIFY ID_Rol INT AUTO_INCREMENT PRIMARY KEY;
ALTER TABLE Permiso MODIFY ID_Permiso INT AUTO_INCREMENT PRIMARY KEY;
ALTER TABLE Rol_Permiso MODIFY ID_Rol_Permiso INT AUTO_INCREMENT PRIMARY KEY;
ALTER TABLE Usuario_Rol MODIFY ID_Usuario_Rol INT AUTO_INCREMENT PRIMARY KEY;
ALTER TABLE Docente MODIFY ID_Docente INT PRIMARY KEY;
ALTER TABLE Estudiante MODIFY ID_Estudiante INT PRIMARY KEY;
ALTER TABLE Asignatura MODIFY ID_Asignatura INT AUTO_INCREMENT PRIMARY KEY;
ALTER TABLE Microcurriculo MODIFY ID_Microcurriculo INT AUTO_INCREMENT PRIMARY KEY;
ALTER TABLE Elemento_ERA MODIFY ID_ERA INT AUTO_INCREMENT PRIMARY KEY;
ALTER TABLE Metodologia MODIFY ID_Metodologia INT AUTO_INCREMENT PRIMARY KEY;
ALTER TABLE Grupo_Investigacion MODIFY ID_Grupo INT AUTO_INCREMENT PRIMARY KEY;
ALTER TABLE Proyecto MODIFY ID_Proyecto INT AUTO_INCREMENT PRIMARY KEY;
ALTER TABLE Proyecto_Asignatura MODIFY ID_Proyecto_Asignatura INT AUTO_INCREMENT PRIMARY KEY;
ALTER TABLE Proyecto_Metodologia MODIFY ID_Proyecto_Metodologia INT AUTO_INCREMENT PRIMARY KEY;
ALTER TABLE Proyecto_Grupo_Investigacion MODIFY ID_Proyecto_Grupo INT AUTO_INCREMENT PRIMARY KEY;
ALTER TABLE Tipo_Entregable MODIFY ID_Tipo_Entregable INT AUTO_INCREMENT PRIMARY KEY;
ALTER TABLE Entregable MODIFY ID_Entregable INT AUTO_INCREMENT PRIMARY KEY;
ALTER TABLE Grupo_Trabajo MODIFY ID_Grupo_Trabajo INT AUTO_INCREMENT PRIMARY KEY;
ALTER TABLE Estudiante_Grupo_Trabajo MODIFY ID_Estudiante_Grupo INT AUTO_INCREMENT PRIMARY KEY;
ALTER TABLE Rubrica_Evaluacion MODIFY ID_Rubrica INT AUTO_INCREMENT PRIMARY KEY;
ALTER TABLE Criterio_Rubrica MODIFY ID_Criterio_Rubrica INT AUTO_INCREMENT PRIMARY KEY;
ALTER TABLE Evaluacion MODIFY ID_Evaluacion INT AUTO_INCREMENT PRIMARY KEY;
ALTER TABLE Resultado_Evaluacion MODIFY ID_Resultado INT AUTO_INCREMENT PRIMARY KEY;
ALTER TABLE Calendario_Entrega MODIFY ID_Calendario INT AUTO_INCREMENT PRIMARY KEY;
ALTER TABLE Requerimiento_Insumo MODIFY ID_Requerimiento INT AUTO_INCREMENT PRIMARY KEY;
ALTER TABLE Notificacion MODIFY ID_Notificacion INT AUTO_INCREMENT PRIMARY KEY;
ALTER TABLE Historial_Cambio MODIFY ID_Historial INT AUTO_INCREMENT PRIMARY KEY;

-- Foreign Keys
ALTER TABLE Departamento ADD FOREIGN KEY (ID_Facultad) REFERENCES Facultad(ID_Facultad);
ALTER TABLE Programa_Academico ADD FOREIGN KEY (ID_Departamento) REFERENCES Departamento(ID_Departamento);
ALTER TABLE Rol_Permiso ADD FOREIGN KEY (ID_Rol) REFERENCES Rol(ID_Rol);
ALTER TABLE Rol_Permiso ADD FOREIGN KEY (ID_Permiso) REFERENCES Permiso(ID_Permiso);
ALTER TABLE Usuario_Rol ADD FOREIGN KEY (ID_Usuario) REFERENCES Usuario(ID_Usuario);
ALTER TABLE Usuario_Rol ADD FOREIGN KEY (ID_Rol) REFERENCES Rol(ID_Rol);
ALTER TABLE Docente ADD FOREIGN KEY (ID_Docente) REFERENCES Usuario(ID_Usuario);
ALTER TABLE Docente ADD FOREIGN KEY (ID_Departamento) REFERENCES Departamento(ID_Departamento);
ALTER TABLE Estudiante ADD FOREIGN KEY (ID_Estudiante) REFERENCES Usuario(ID_Usuario);
ALTER TABLE Estudiante ADD FOREIGN KEY (ID_Programa) REFERENCES Programa_Academico(ID_Programa);
ALTER TABLE Asignatura ADD FOREIGN KEY (ID_Programa) REFERENCES Programa_Academico(ID_Programa);
ALTER TABLE Microcurriculo ADD FOREIGN KEY (ID_Asignatura) REFERENCES Asignatura(ID_Asignatura);
ALTER TABLE Elemento_ERA ADD FOREIGN KEY (ID_Microcurriculo) REFERENCES Microcurriculo(ID_Microcurriculo);
ALTER TABLE Grupo_Investigacion ADD FOREIGN KEY (ID_Departamento) REFERENCES Departamento(ID_Departamento);
ALTER TABLE Proyecto ADD FOREIGN KEY (ID_Docente_Responsable) REFERENCES Docente(ID_Docente);
ALTER TABLE Proyecto_Asignatura ADD FOREIGN KEY (ID_Proyecto) REFERENCES Proyecto(ID_Proyecto);
ALTER TABLE Proyecto_Asignatura ADD FOREIGN KEY (ID_Asignatura) REFERENCES Asignatura(ID_Asignatura);
ALTER TABLE Proyecto_Metodologia ADD FOREIGN KEY (ID_Proyecto) REFERENCES Proyecto(ID_Proyecto);
ALTER TABLE Proyecto_Metodologia ADD FOREIGN KEY (ID_Metodologia) REFERENCES Metodologia(ID_Metodologia);
ALTER TABLE Proyecto_Grupo_Investigacion ADD FOREIGN KEY (ID_Proyecto) REFERENCES Proyecto(ID_Proyecto);
ALTER TABLE Proyecto_Grupo_Investigacion ADD FOREIGN KEY (ID_Grupo) REFERENCES Grupo_Investigacion(ID_Grupo);
ALTER TABLE Entregable ADD FOREIGN KEY (ID_Proyecto) REFERENCES Proyecto(ID_Proyecto);
ALTER TABLE Entregable ADD FOREIGN KEY (ID_Tipo_Entregable) REFERENCES Tipo_Entregable(ID_Tipo_Entregable);
ALTER TABLE Grupo_Trabajo ADD FOREIGN KEY (ID_Proyecto) REFERENCES Proyecto(ID_Proyecto);
ALTER TABLE Grupo_Trabajo ADD FOREIGN KEY (ID_Estudiante_Lider) REFERENCES Estudiante(ID_Estudiante);
ALTER TABLE Estudiante_Grupo_Trabajo ADD FOREIGN KEY (ID_Estudiante) REFERENCES Estudiante(ID_Estudiante);
ALTER TABLE Estudiante_Grupo_Trabajo ADD FOREIGN KEY (ID_Grupo_Trabajo) REFERENCES Grupo_Trabajo(ID_Grupo_Trabajo);
ALTER TABLE Rubrica_Evaluacion ADD FOREIGN KEY (ID_ERA) REFERENCES Elemento_ERA(ID_ERA);
ALTER TABLE Criterio_Rubrica ADD FOREIGN KEY (ID_Rubrica) REFERENCES Rubrica_Evaluacion(ID_Rubrica);
ALTER TABLE Evaluacion ADD FOREIGN KEY (ID_Proyecto) REFERENCES Proyecto(ID_Proyecto);
ALTER TABLE Evaluacion ADD FOREIGN KEY (ID_Rubrica) REFERENCES Rubrica_Evaluacion(ID_Rubrica);
ALTER TABLE Resultado_Evaluacion ADD FOREIGN KEY (ID_Evaluacion) REFERENCES Evaluacion(ID_Evaluacion);
ALTER TABLE Resultado_Evaluacion ADD FOREIGN KEY (ID_Grupo_Trabajo) REFERENCES Grupo_Trabajo(ID_Grupo_Trabajo);
ALTER TABLE Calendario_Entrega ADD FOREIGN KEY (ID_Proyecto) REFERENCES Proyecto(ID_Proyecto);
ALTER TABLE Requerimiento_Insumo ADD FOREIGN KEY (ID_Proyecto) REFERENCES Proyecto(ID_Proyecto);
ALTER TABLE Notificacion ADD FOREIGN KEY (ID_Usuario_Destino) REFERENCES Usuario(ID_Usuario);
ALTER TABLE Historial_Cambio ADD FOREIGN KEY (ID_Usuario) REFERENCES Usuario(ID_Usuario);

-- Unique Keys
ALTER TABLE Usuario ADD UNIQUE (Correo);
ALTER TABLE Rol ADD UNIQUE (Nombre);
ALTER TABLE Permiso ADD UNIQUE (Nombre);
ALTER TABLE Rol_Permiso ADD UNIQUE (ID_Rol, ID_Permiso);
ALTER TABLE Usuario_Rol ADD UNIQUE (ID_Usuario, ID_Rol);
ALTER TABLE Estudiante ADD UNIQUE (Matricula);
ALTER TABLE Asignatura ADD UNIQUE (Codigo);
ALTER TABLE Microcurriculo ADD UNIQUE (ID_Asignatura);
ALTER TABLE Metodologia ADD UNIQUE (Nombre);
ALTER TABLE Grupo_Investigacion ADD UNIQUE (Nombre);
ALTER TABLE Elemento_ERA ADD UNIQUE (ID_Microcurriculo, Codigo);
ALTER TABLE Proyecto_Asignatura ADD UNIQUE (ID_Proyecto, ID_Asignatura);
ALTER TABLE Proyecto_Metodologia ADD UNIQUE (ID_Proyecto, ID_Metodologia);
ALTER TABLE Proyecto_Grupo_Investigacion ADD UNIQUE (ID_Proyecto, ID_Grupo);
ALTER TABLE Grupo_Trabajo ADD UNIQUE (ID_Proyecto, Nombre);
ALTER TABLE Estudiante_Grupo_Trabajo ADD UNIQUE (ID_Estudiante, ID_Grupo_Trabajo);
ALTER TABLE Resultado_Evaluacion ADD UNIQUE (ID_Evaluacion, ID_Grupo_Trabajo);