
-- NOT NULL Constraints
ALTER TABLE Facultad MODIFY Nombre VARCHAR(100) NOT NULL;
ALTER TABLE Departamento MODIFY Nombre VARCHAR(100) NOT NULL;
ALTER TABLE Departamento MODIFY ID_Facultad INT NOT NULL;
ALTER TABLE Programa_Academico MODIFY Nombre VARCHAR(150) NOT NULL;
ALTER TABLE Programa_Academico MODIFY Nivel_Estudio VARCHAR(50) NOT NULL;
ALTER TABLE Programa_Academico MODIFY ID_Departamento INT NOT NULL;
ALTER TABLE Usuario MODIFY Nombre VARCHAR(100) NOT NULL;
ALTER TABLE Usuario MODIFY Apellido VARCHAR(100) NOT NULL;
ALTER TABLE Usuario MODIFY Correo VARCHAR(150) NOT NULL;
ALTER TABLE Usuario MODIFY Contrasena VARCHAR(255) NOT NULL;
ALTER TABLE Rol MODIFY Nombre VARCHAR(50) NOT NULL;
ALTER TABLE Permiso MODIFY Nombre VARCHAR(50) NOT NULL;
ALTER TABLE Docente MODIFY ID_Departamento INT NOT NULL;
ALTER TABLE Estudiante MODIFY ID_Programa INT NOT NULL;
ALTER TABLE Estudiante MODIFY Semestre INT NOT NULL;
ALTER TABLE Estudiante MODIFY Matricula VARCHAR(20) NOT NULL;
ALTER TABLE Asignatura MODIFY Codigo VARCHAR(20) NOT NULL;
ALTER TABLE Asignatura MODIFY Nombre VARCHAR(150) NOT NULL;
ALTER TABLE Asignatura MODIFY Creditos INT NOT NULL;
ALTER TABLE Asignatura MODIFY Horas_Teoricas INT NOT NULL;
ALTER TABLE Asignatura MODIFY Horas_Practicas INT NOT NULL;
ALTER TABLE Asignatura MODIFY ID_Programa INT NOT NULL;
ALTER TABLE Microcurriculo MODIFY ID_Asignatura INT NOT NULL;
ALTER TABLE Microcurriculo MODIFY Justificacion TEXT NOT NULL;
ALTER TABLE Microcurriculo MODIFY Problematizacion TEXT NOT NULL;
ALTER TABLE Microcurriculo MODIFY Objetivo_General TEXT NOT NULL;
ALTER TABLE Elemento_ERA MODIFY ID_Microcurriculo INT NOT NULL;
ALTER TABLE Elemento_ERA MODIFY Codigo VARCHAR(20) NOT NULL;
ALTER TABLE Elemento_ERA MODIFY Descripcion TEXT NOT NULL;
ALTER TABLE Elemento_ERA MODIFY Criterios_Saber TEXT NOT NULL;
ALTER TABLE Elemento_ERA MODIFY Criterios_Hacer TEXT NOT NULL;
ALTER TABLE Elemento_ERA MODIFY Criterios_Ser TEXT NOT NULL;
ALTER TABLE Metodologia MODIFY Nombre VARCHAR(100) NOT NULL;
ALTER TABLE Grupo_Investigacion MODIFY Nombre VARCHAR(150) NOT NULL;
ALTER TABLE Grupo_Investigacion MODIFY Linea_Investigacion VARCHAR(150) NOT NULL;
ALTER TABLE Grupo_Investigacion MODIFY ID_Departamento INT NOT NULL;
ALTER TABLE Proyecto MODIFY Titulo VARCHAR(200) NOT NULL;
ALTER TABLE Proyecto MODIFY Descripcion TEXT NOT NULL;
ALTER TABLE Proyecto MODIFY Tipo CHAR(3) NOT NULL;
ALTER TABLE Proyecto MODIFY Fecha_Inicio DATE NOT NULL;
ALTER TABLE Proyecto MODIFY Fecha_Fin DATE NOT NULL;
ALTER TABLE Proyecto MODIFY Estado VARCHAR(20) NOT NULL;
ALTER TABLE Proyecto MODIFY ID_Docente_Responsable INT NOT NULL;
ALTER TABLE Entregable MODIFY ID_Proyecto INT NOT NULL;
ALTER TABLE Entregable MODIFY ID_Tipo_Entregable INT NOT NULL;
ALTER TABLE Entregable MODIFY Descripcion TEXT NOT NULL;
ALTER TABLE Entregable MODIFY Fecha_Entrega DATE NOT NULL;
ALTER TABLE Entregable MODIFY Estado VARCHAR(20) NOT NULL;
ALTER TABLE Grupo_Trabajo MODIFY ID_Proyecto INT NOT NULL;
ALTER TABLE Grupo_Trabajo MODIFY Nombre VARCHAR(100) NOT NULL;
ALTER TABLE Grupo_Trabajo MODIFY ID_Estudiante_Lider INT NOT NULL;
ALTER TABLE Estudiante_Grupo_Trabajo MODIFY ID_Estudiante INT NOT NULL;
ALTER TABLE Estudiante_Grupo_Trabajo MODIFY ID_Grupo_Trabajo INT NOT NULL;
ALTER TABLE Estudiante_Grupo_Trabajo MODIFY Rol VARCHAR(50) NOT NULL;
ALTER TABLE Rubrica_Evaluacion MODIFY ID_ERA INT NOT NULL;
ALTER TABLE Rubrica_Evaluacion MODIFY Nombre VARCHAR(150) NOT NULL;
ALTER TABLE Criterio_Rubrica MODIFY ID_Rubrica INT NOT NULL;
ALTER TABLE Criterio_Rubrica MODIFY Descripcion TEXT NOT NULL;
ALTER TABLE Criterio_Rubrica MODIFY Niveles_Desempeno JSON NOT NULL;
ALTER TABLE Evaluacion MODIFY ID_Proyecto INT NOT NULL;
ALTER TABLE Evaluacion MODIFY ID_Rubrica INT NOT NULL;
ALTER TABLE Evaluacion MODIFY Tipo_Evaluacion VARCHAR(50) NOT NULL;
ALTER TABLE Evaluacion MODIFY Fecha_Evaluacion DATE NOT NULL;
ALTER TABLE Evaluacion MODIFY Periodo_Academico VARCHAR(20) NOT NULL;
ALTER TABLE Resultado_Evaluacion MODIFY ID_Evaluacion INT NOT NULL;
ALTER TABLE Resultado_Evaluacion MODIFY ID_Grupo_Trabajo INT NOT NULL;
ALTER TABLE Resultado_Evaluacion MODIFY Calificacion DECIMAL(3,1) NOT NULL;
ALTER TABLE Calendario_Entrega MODIFY ID_Proyecto INT NOT NULL;
ALTER TABLE Calendario_Entrega MODIFY Tipo_Evento VARCHAR(50) NOT NULL;
ALTER TABLE Calendario_Entrega MODIFY Fecha_Hora_Inicio DATETIME NOT NULL;
ALTER TABLE Calendario_Entrega MODIFY Fecha_Hora_Fin DATETIME NOT NULL;
ALTER TABLE Calendario_Entrega MODIFY Descripcion TEXT NOT NULL;
ALTER TABLE Requerimiento_Insumo MODIFY ID_Proyecto INT NOT NULL;
ALTER TABLE Requerimiento_Insumo MODIFY Descripcion TEXT NOT NULL;
ALTER TABLE Requerimiento_Insumo MODIFY Cantidad INT NOT NULL;
ALTER TABLE Requerimiento_Insumo MODIFY Unidad_Medida VARCHAR(20) NOT NULL;
ALTER TABLE Requerimiento_Insumo MODIFY Estado VARCHAR(20) NOT NULL;
ALTER TABLE Notificacion MODIFY ID_Usuario_Destino INT NOT NULL;
ALTER TABLE Notificacion MODIFY Titulo VARCHAR(150) NOT NULL;
ALTER TABLE Notificacion MODIFY Mensaje TEXT NOT NULL;
ALTER TABLE Notificacion MODIFY Tipo VARCHAR(50) NOT NULL;
ALTER TABLE Historial_Cambio MODIFY ID_Usuario INT NOT NULL;
ALTER TABLE Historial_Cambio MODIFY Tabla_Afectada VARCHAR(50) NOT NULL;
ALTER TABLE Historial_Cambio MODIFY ID_Registro_Afectado INT NOT NULL;
ALTER TABLE Historial_Cambio MODIFY Accion VARCHAR(20) NOT NULL;
ALTER TABLE Historial_Cambio MODIFY fecha DATETIME NOT NULL;

-- CHECK Constraints
ALTER TABLE Programa_Academico ADD CONSTRAINT chk_nivel_estudio CHECK (Nivel_Estudio IN ('Pregrado', 'Posgrado', 'Técnico', 'Tecnólogo'));
ALTER TABLE Estudiante ADD CONSTRAINT chk_semestre CHECK (Semestre > 0);
ALTER TABLE Asignatura ADD CONSTRAINT chk_creditos CHECK (Creditos > 0);
ALTER TABLE Proyecto ADD CONSTRAINT chk_tipo_proyecto CHECK (Tipo IN ('PA', 'PIA'));
ALTER TABLE Proyecto ADD CONSTRAINT chk_estado_proyecto CHECK (Estado IN ('Borrador', 'Activo', 'Finalizado', 'Cancelado'));
ALTER TABLE Proyecto ADD CONSTRAINT chk_fechas_proyecto CHECK (Fecha_Fin > Fecha_Inicio);
ALTER TABLE Entregable ADD CONSTRAINT chk_estado_entregable CHECK (Estado IN ('Pendiente', 'Entregado', 'Aprobado', 'Rechazado'));
ALTER TABLE Evaluacion ADD CONSTRAINT chk_tipo_evaluacion CHECK (Tipo_Evaluacion IN ('Autoevaluación', 'Coevaluación', 'Heteroevaluación'));
ALTER TABLE Resultado_Evaluacion ADD CONSTRAINT chk_calificacion CHECK (Calificacion >= 0 AND Calificacion <= 5.0);
ALTER TABLE Calendario_Entrega ADD CONSTRAINT chk_tipo_evento CHECK (Tipo_Evento IN ('Entrega', 'Revisión', 'Sesión', 'Presentación'));
ALTER TABLE Calendario_Entrega ADD CONSTRAINT chk_fechas_calendario CHECK (Fecha_Hora_Fin > Fecha_Hora_Inicio);
ALTER TABLE Requerimiento_Insumo ADD CONSTRAINT chk_cantidad CHECK (Cantidad > 0);
ALTER TABLE Requerimiento_Insumo ADD CONSTRAINT chk_estado_requerimiento CHECK (Estado IN ('Solicitado', 'Aprobado', 'Rechazado', 'Entregado'));
ALTER TABLE Notificacion ADD CONSTRAINT chk_tipo_notificacion CHECK (Tipo IN ('Sistema', 'Mensaje', 'Alerta', 'Recordatorio'));
ALTER TABLE Historial_Cambio ADD CONSTRAINT chk_accion CHECK (Accion IN ('INSERT', 'UPDATE', 'DELETE'));

-- DEFAULT Values
ALTER TABLE Usuario MODIFY Activo BOOLEAN DEFAULT TRUE;
ALTER TABLE Usuario MODIFY Fecha_Registro TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE Microcurriculo MODIFY Fecha_Actualizacion DATE DEFAULT (CURRENT_DATE);
ALTER TABLE Rubrica_Evaluacion MODIFY Fecha_Creacion DATE DEFAULT (CURRENT_DATE);
ALTER TABLE Requerimiento_Insumo MODIFY Fecha_Solicitud DATE DEFAULT (CURRENT_DATE);
ALTER TABLE Notificacion MODIFY Fecha_Envio TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE Notificacion MODIFY Leida BOOLEAN DEFAULT FALSE;