
-- Primary Keys
ALTER TABLE Facultad ADD PRIMARY KEY (ID_Facultad);
ALTER TABLE Departamento ADD PRIMARY KEY (ID_Departamento);
ALTER TABLE Programa_Academico ADD PRIMARY KEY (ID_Programa);
ALTER TABLE Usuario ADD PRIMARY KEY (ID_Usuario);
ALTER TABLE Rol ADD PRIMARY KEY (ID_Rol);
ALTER TABLE Permiso ADD PRIMARY KEY (ID_Permiso);
ALTER TABLE Rol_Permiso ADD PRIMARY KEY (ID_Rol_Permiso);
ALTER TABLE Usuario_Rol ADD PRIMARY KEY (ID_Usuario_Rol);
ALTER TABLE Docente ADD PRIMARY KEY (ID_Docente);
ALTER TABLE Estudiante ADD PRIMARY KEY (ID_Estudiante);
ALTER TABLE Asignatura ADD PRIMARY KEY (ID_Asignatura);
ALTER TABLE Microcurriculo ADD PRIMARY KEY (ID_Microcurriculo);
ALTER TABLE Elemento_ERA ADD PRIMARY KEY (ID_ERA);
ALTER TABLE Metodologia ADD PRIMARY KEY (ID_Metodologia);
ALTER TABLE Grupo_Investigacion ADD PRIMARY KEY (ID_Grupo);
ALTER TABLE Proyecto ADD PRIMARY KEY (ID_Proyecto);
ALTER TABLE Proyecto_Asignatura ADD PRIMARY KEY (ID_Proyecto_Asignatura);
ALTER TABLE Proyecto_Metodologia ADD PRIMARY KEY (ID_Proyecto_Metodologia);
ALTER TABLE Proyecto_Grupo_Investigacion ADD PRIMARY KEY (ID_Proyecto_Grupo);
ALTER TABLE Tipo_Entregable ADD PRIMARY KEY (ID_Tipo_Entregable);
ALTER TABLE Entregable ADD PRIMARY KEY (ID_Entregable);
ALTER TABLE Grupo_Trabajo ADD PRIMARY KEY (ID_Grupo_Trabajo);
ALTER TABLE Estudiante_Grupo_Trabajo ADD PRIMARY KEY (ID_Estudiante_Grupo);
ALTER TABLE Rubrica_Evaluacion ADD PRIMARY KEY (ID_Rubrica);
ALTER TABLE Criterio_Rubrica ADD PRIMARY KEY (ID_Criterio_Rubrica);
ALTER TABLE Evaluacion ADD PRIMARY KEY (ID_Evaluacion);
ALTER TABLE Resultado_Evaluacion ADD PRIMARY KEY (ID_Resultado);
ALTER TABLE Calendario_Entrega ADD PRIMARY KEY (ID_Calendario);
ALTER TABLE Requerimiento_Insumo ADD PRIMARY KEY (ID_Requerimiento);
ALTER TABLE Notificacion ADD PRIMARY KEY (ID_Notificacion);
ALTER TABLE Historial_Cambio ADD PRIMARY KEY (ID_Historial);

-- Foreign Keys
ALTER TABLE Departamento ADD CONSTRAINT fk_departamento_facultad FOREIGN KEY (ID_Facultad) REFERENCES Facultad(ID_Facultad);
ALTER TABLE Programa_Academico ADD CONSTRAINT fk_programa_departamento FOREIGN KEY (ID_Departamento) REFERENCES Departamento(ID_Departamento);
ALTER TABLE Rol_Permiso ADD CONSTRAINT fk_rol_permiso_rol FOREIGN KEY (ID_Rol) REFERENCES Rol(ID_Rol);
ALTER TABLE Rol_Permiso ADD CONSTRAINT fk_rol_permiso_permiso FOREIGN KEY (ID_Permiso) REFERENCES Permiso(ID_Permiso);
ALTER TABLE Usuario_Rol ADD CONSTRAINT fk_usuario_rol_usuario FOREIGN KEY (ID_Usuario) REFERENCES Usuario(ID_Usuario);
ALTER TABLE Usuario_Rol ADD CONSTRAINT fk_usuario_rol_rol FOREIGN KEY (ID_Rol) REFERENCES Rol(ID_Rol);
ALTER TABLE Docente ADD CONSTRAINT fk_docente_usuario FOREIGN KEY (ID_Docente) REFERENCES Usuario(ID_Usuario);
ALTER TABLE Docente ADD CONSTRAINT fk_docente_departamento FOREIGN KEY (ID_Departamento) REFERENCES Departamento(ID_Departamento);
ALTER TABLE Estudiante ADD CONSTRAINT fk_estudiante_usuario FOREIGN KEY (ID_Estudiante) REFERENCES Usuario(ID_Usuario);
ALTER TABLE Estudiante ADD CONSTRAINT fk_estudiante_programa FOREIGN KEY (ID_Programa) REFERENCES Programa_Academico(ID_Programa);
ALTER TABLE Asignatura ADD CONSTRAINT fk_asignatura_programa FOREIGN KEY (ID_Programa) REFERENCES Programa_Academico(ID_Programa);
ALTER TABLE Microcurriculo ADD CONSTRAINT fk_microcurriculo_asignatura FOREIGN KEY (ID_Asignatura) REFERENCES Asignatura(ID_Asignatura);
ALTER TABLE Elemento_ERA ADD CONSTRAINT fk_era_microcurriculo FOREIGN KEY (ID_Microcurriculo) REFERENCES Microcurriculo(ID_Microcurriculo);
ALTER TABLE Grupo_Investigacion ADD CONSTRAINT fk_grupo_departamento FOREIGN KEY (ID_Departamento) REFERENCES Departamento(ID_Departamento);
ALTER TABLE Proyecto ADD CONSTRAINT fk_proyecto_docente FOREIGN KEY (ID_Docente_Responsable) REFERENCES Docente(ID_Docente);
ALTER TABLE Proyecto_Asignatura ADD CONSTRAINT fk_proyecto_asignatura_proyecto FOREIGN KEY (ID_Proyecto) REFERENCES Proyecto(ID_Proyecto);
ALTER TABLE Proyecto_Asignatura ADD CONSTRAINT fk_proyecto_asignatura_asignatura FOREIGN KEY (ID_Asignatura) REFERENCES Asignatura(ID_Asignatura);
ALTER TABLE Proyecto_Metodologia ADD CONSTRAINT fk_proyecto_metodologia_proyecto FOREIGN KEY (ID_Proyecto) REFERENCES Proyecto(ID_Proyecto);
ALTER TABLE Proyecto_Metodologia ADD CONSTRAINT fk_proyecto_metodologia_metodologia FOREIGN KEY (ID_Metodologia) REFERENCES Metodologia(ID_Metodologia);
ALTER TABLE Proyecto_Grupo_Investigacion ADD CONSTRAINT fk_proyecto_grupo_proyecto FOREIGN KEY (ID_Proyecto) REFERENCES Proyecto(ID_Proyecto);
ALTER TABLE Proyecto_Grupo_Investigacion ADD CONSTRAINT fk_proyecto_grupo_grupo FOREIGN KEY (ID_Grupo) REFERENCES Grupo_Investigacion(ID_Grupo);
ALTER TABLE Entregable ADD CONSTRAINT fk_entregable_proyecto FOREIGN KEY (ID_Proyecto) REFERENCES Proyecto(ID_Proyecto);
ALTER TABLE Entregable ADD CONSTRAINT fk_entregable_tipo FOREIGN KEY (ID_Tipo_Entregable) REFERENCES Tipo_Entregable(ID_Tipo_Entregable);
ALTER TABLE Grupo_Trabajo ADD CONSTRAINT fk_grupo_trabajo_proyecto FOREIGN KEY (ID_Proyecto) REFERENCES Proyecto(ID_Proyecto);
ALTER TABLE Grupo_Trabajo ADD CONSTRAINT fk_grupo_trabajo_lider FOREIGN KEY (ID_Estudiante_Lider) REFERENCES Estudiante(ID_Estudiante);
ALTER TABLE Estudiante_Grupo_Trabajo ADD CONSTRAINT fk_estudiante_grupo_estudiante FOREIGN KEY (ID_Estudiante) REFERENCES Estudiante(ID_Estudiante);
ALTER TABLE Estudiante_Grupo_Trabajo ADD CONSTRAINT fk_estudiante_grupo_grupo FOREIGN KEY (ID_Grupo_Trabajo) REFERENCES Grupo_Trabajo(ID_Grupo_Trabajo);
ALTER TABLE Rubrica_Evaluacion ADD CONSTRAINT fk_rubrica_era FOREIGN KEY (ID_ERA) REFERENCES Elemento_ERA(ID_ERA);
ALTER TABLE Criterio_Rubrica ADD CONSTRAINT fk_criterio_rubrica FOREIGN KEY (ID_Rubrica) REFERENCES Rubrica_Evaluacion(ID_Rubrica);
ALTER TABLE Evaluacion ADD CONSTRAINT fk_evaluacion_proyecto FOREIGN KEY (ID_Proyecto) REFERENCES Proyecto(ID_Proyecto);
ALTER TABLE Evaluacion ADD CONSTRAINT fk_evaluacion_rubrica FOREIGN KEY (ID_Rubrica) REFERENCES Rubrica_Evaluacion(ID_Rubrica);
ALTER TABLE Resultado_Evaluacion ADD CONSTRAINT fk_resultado_evaluacion FOREIGN KEY (ID_Evaluacion) REFERENCES Evaluacion(ID_Evaluacion);
ALTER TABLE Resultado_Evaluacion ADD CONSTRAINT fk_resultado_grupo FOREIGN KEY (ID_Grupo_Trabajo) REFERENCES Grupo_Trabajo(ID_Grupo_Trabajo);
ALTER TABLE Calendario_Entrega ADD CONSTRAINT fk_calendario_proyecto FOREIGN KEY (ID_Proyecto) REFERENCES Proyecto(ID_Proyecto);
ALTER TABLE Requerimiento_Insumo ADD CONSTRAINT fk_requerimiento_proyecto FOREIGN KEY (ID_Proyecto) REFERENCES Proyecto(ID_Proyecto);
ALTER TABLE Notificacion ADD CONSTRAINT fk_notificacion_usuario FOREIGN KEY (ID_Usuario_Destino) REFERENCES Usuario(ID_Usuario);
ALTER TABLE Historial_Cambio ADD CONSTRAINT fk_historial_usuario FOREIGN KEY (ID_Usuario) REFERENCES Usuario(ID_Usuario);

-- Unique Keys
ALTER TABLE Usuario ADD CONSTRAINT uk_usuario_correo UNIQUE (Correo);
ALTER TABLE Rol ADD CONSTRAINT uk_rol_nombre UNIQUE (Nombre);
ALTER TABLE Permiso ADD CONSTRAINT uk_permiso_nombre UNIQUE (Nombre);
ALTER TABLE Rol_Permiso ADD CONSTRAINT uk_rol_permiso UNIQUE (ID_Rol, ID_Permiso);
ALTER TABLE Usuario_Rol ADD CONSTRAINT uk_usuario_rol UNIQUE (ID_Usuario, ID_Rol);
ALTER TABLE Estudiante ADD CONSTRAINT uk_estudiante_matricula UNIQUE (Matricula);
ALTER TABLE Asignatura ADD CONSTRAINT uk_asignatura_codigo UNIQUE (Codigo);
ALTER TABLE Microcurriculo ADD CONSTRAINT uk_microcurriculo_asignatura UNIQUE (ID_Asignatura);
ALTER TABLE Metodologia ADD CONSTRAINT uk_metodologia_nombre UNIQUE (Nombre);
ALTER TABLE Grupo_Investigacion ADD CONSTRAINT uk_grupo_nombre UNIQUE (Nombre);
ALTER TABLE Elemento_ERA ADD CONSTRAINT uk_era_microcurriculo_codigo UNIQUE (ID_Microcurriculo, Codigo);
ALTER TABLE Proyecto_Asignatura ADD CONSTRAINT uk_proyecto_asignatura UNIQUE (ID_Proyecto, ID_Asignatura);
ALTER TABLE Proyecto_Metodologia ADD CONSTRAINT uk_proyecto_metodologia UNIQUE (ID_Proyecto, ID_Metodologia);
ALTER TABLE Proyecto_Grupo_Investigacion ADD CONSTRAINT uk_proyecto_grupo UNIQUE (ID_Proyecto, ID_Grupo);
ALTER TABLE Grupo_Trabajo ADD CONSTRAINT uk_grupo_trabajo_nombre UNIQUE (ID_Proyecto, Nombre);
ALTER TABLE Estudiante_Grupo_Trabajo ADD CONSTRAINT uk_estudiante_grupo UNIQUE (ID_Estudiante, ID_Grupo_Trabajo);
ALTER TABLE Resultado_Evaluacion ADD CONSTRAINT uk_resultado_evaluacion_grupo UNIQUE (ID_Evaluacion, ID_Grupo_Trabajo);