
-- NOT NULL Constraints
ALTER TABLE Facultad ALTER COLUMN Nombre SET NOT NULL;
ALTER TABLE Departamento ALTER COLUMN Nombre SET NOT NULL;
ALTER TABLE Departamento ALTER COLUMN ID_Facultad SET NOT NULL;
ALTER TABLE Programa_Academico ALTER COLUMN Nombre SET NOT NULL;
ALTER TABLE Programa_Academico ALTER COLUMN Nivel_Estudio SET NOT NULL;
ALTER TABLE Programa_Academico ALTER COLUMN ID_Departamento SET NOT NULL;
ALTER TABLE Usuario ALTER COLUMN Nombre SET NOT NULL;
ALTER TABLE Usuario ALTER COLUMN Apellido SET NOT NULL;
ALTER TABLE Usuario ALTER COLUMN Correo SET NOT NULL;
ALTER TABLE Usuario ALTER COLUMN Contrasena SET NOT NULL;
ALTER TABLE Rol ALTER COLUMN Nombre SET NOT NULL;
ALTER TABLE Permiso ALTER COLUMN Nombre SET NOT NULL;
ALTER TABLE Docente ALTER COLUMN ID_Departamento SET NOT NULL;
ALTER TABLE Estudiante ALTER COLUMN ID_Programa SET NOT NULL;
ALTER TABLE Estudiante ALTER COLUMN Semestre SET NOT NULL;
ALTER TABLE Estudiante ALTER COLUMN Matricula SET NOT NULL;
ALTER TABLE Asignatura ALTER COLUMN Codigo SET NOT NULL;
ALTER TABLE Asignatura ALTER COLUMN Nombre SET NOT NULL;
ALTER TABLE Asignatura ALTER COLUMN Creditos SET NOT NULL;
ALTER TABLE Asignatura ALTER COLUMN Horas_Teoricas SET NOT NULL;
ALTER TABLE Asignatura ALTER COLUMN Horas_Practicas SET NOT NULL;
ALTER TABLE Asignatura ALTER COLUMN ID_Programa SET NOT NULL;
ALTER TABLE Microcurriculo ALTER COLUMN ID_Asignatura SET NOT NULL;
ALTER TABLE Microcurriculo ALTER COLUMN Justificacion SET NOT NULL;
ALTER TABLE Microcurriculo ALTER COLUMN Problematizacion SET NOT NULL;
ALTER TABLE Microcurriculo ALTER COLUMN Objetivo_General SET NOT NULL;
ALTER TABLE Elemento_ERA ALTER COLUMN ID_Microcurriculo SET NOT NULL;
ALTER TABLE Elemento_ERA ALTER COLUMN Codigo SET NOT NULL;
ALTER TABLE Elemento_ERA ALTER COLUMN Descripcion SET NOT NULL;
ALTER TABLE Elemento_ERA ALTER COLUMN Criterios_Saber SET NOT NULL;
ALTER TABLE Elemento_ERA ALTER COLUMN Criterios_Hacer SET NOT NULL;
ALTER TABLE Elemento_ERA ALTER COLUMN Criterios_Ser SET NOT NULL;
ALTER TABLE Metodologia ALTER COLUMN Nombre SET NOT NULL;
ALTER TABLE Grupo_Investigacion ALTER COLUMN Nombre SET NOT NULL;
ALTER TABLE Grupo_Investigacion ALTER COLUMN Linea_Investigacion SET NOT NULL;
ALTER TABLE Grupo_Investigacion ALTER COLUMN ID_Departamento SET NOT NULL;
ALTER TABLE Proyecto ALTER COLUMN Titulo SET NOT NULL;
ALTER TABLE Proyecto ALTER COLUMN Descripcion SET NOT NULL;
ALTER TABLE Proyecto ALTER COLUMN Tipo SET NOT NULL;
ALTER TABLE Proyecto ALTER COLUMN Fecha_Inicio SET NOT NULL;
ALTER TABLE Proyecto ALTER COLUMN Fecha_Fin SET NOT NULL;
ALTER TABLE Proyecto ALTER COLUMN Estado SET NOT NULL;
ALTER TABLE Proyecto ALTER COLUMN ID_Docente_Responsable SET NOT NULL;
ALTER TABLE Entregable ALTER COLUMN ID_Proyecto SET NOT NULL;
ALTER TABLE Entregable ALTER COLUMN ID_Tipo_Entregable SET NOT NULL;
ALTER TABLE Entregable ALTER COLUMN Descripcion SET NOT NULL;
ALTER TABLE Entregable ALTER COLUMN Fecha_Entrega SET NOT NULL;
ALTER TABLE Entregable ALTER COLUMN Estado SET NOT NULL;
ALTER TABLE Grupo_Trabajo ALTER COLUMN ID_Proyecto SET NOT NULL;
ALTER TABLE Grupo_Trabajo ALTER COLUMN Nombre SET NOT NULL;
ALTER TABLE Grupo_Trabajo ALTER COLUMN ID_Estudiante_Lider SET NOT NULL;
ALTER TABLE Estudiante_Grupo_Trabajo ALTER COLUMN ID_Estudiante SET NOT NULL;
ALTER TABLE Estudiante_Grupo_Trabajo ALTER COLUMN ID_Grupo_Trabajo SET NOT NULL;
ALTER TABLE Estudiante_Grupo_Trabajo ALTER COLUMN Rol SET NOT NULL;
ALTER TABLE Rubrica_Evaluacion ALTER COLUMN ID_ERA SET NOT NULL;
ALTER TABLE Rubrica_Evaluacion ALTER COLUMN Nombre SET NOT NULL;
ALTER TABLE Criterio_Rubrica ALTER COLUMN ID_Rubrica SET NOT NULL;
ALTER TABLE Criterio_Rubrica ALTER COLUMN Descripcion SET NOT NULL;
ALTER TABLE Criterio_Rubrica ALTER COLUMN Niveles_Desempeno SET NOT NULL;
ALTER TABLE Evaluacion ALTER COLUMN ID_Proyecto SET NOT NULL;
ALTER TABLE Evaluacion ALTER COLUMN ID_Rubrica SET NOT NULL;
ALTER TABLE Evaluacion ALTER COLUMN Tipo_Evaluacion SET NOT NULL;
ALTER TABLE Evaluacion ALTER COLUMN Fecha_Evaluacion SET NOT NULL;
ALTER TABLE Evaluacion ALTER COLUMN Periodo_Academico SET NOT NULL;
ALTER TABLE Resultado_Evaluacion ALTER COLUMN ID_Evaluacion SET NOT NULL;
ALTER TABLE Resultado_Evaluacion ALTER COLUMN ID_Grupo_Trabajo SET NOT NULL;
ALTER TABLE Resultado_Evaluacion ALTER COLUMN Calificacion SET NOT NULL;
ALTER TABLE Calendario_Entrega ALTER COLUMN ID_Proyecto SET NOT NULL;
ALTER TABLE Calendario_Entrega ALTER COLUMN Tipo_Evento SET NOT NULL;
ALTER TABLE Calendario_Entrega ALTER COLUMN Fecha_Hora_Inicio SET NOT NULL;
ALTER TABLE Calendario_Entrega ALTER COLUMN Fecha_Hora_Fin SET NOT NULL;
ALTER TABLE Calendario_Entrega ALTER COLUMN Descripcion SET NOT NULL;
ALTER TABLE Requerimiento_Insumo ALTER COLUMN ID_Proyecto SET NOT NULL;
ALTER TABLE Requerimiento_Insumo ALTER COLUMN Descripcion SET NOT NULL;
ALTER TABLE Requerimiento_Insumo ALTER COLUMN Cantidad SET NOT NULL;
ALTER TABLE Requerimiento_Insumo ALTER COLUMN Unidad_Medida SET NOT NULL;
ALTER TABLE Requerimiento_Insumo ALTER COLUMN Estado SET NOT NULL;
ALTER TABLE Notificacion ALTER COLUMN ID_Usuario_Destino SET NOT NULL;
ALTER TABLE Notificacion ALTER COLUMN Titulo SET NOT NULL;
ALTER TABLE Notificacion ALTER COLUMN Mensaje SET NOT NULL;
ALTER TABLE Notificacion ALTER COLUMN Tipo SET NOT NULL;
ALTER TABLE Historial_Cambio ALTER COLUMN ID_Usuario SET NOT NULL;
ALTER TABLE Historial_Cambio ALTER COLUMN Tabla_Afectada SET NOT NULL;
ALTER TABLE Historial_Cambio ALTER COLUMN ID_Registro_Afectado SET NOT NULL;
ALTER TABLE Historial_Cambio ALTER COLUMN Accion SET NOT NULL;

-- CHECK Constraints
ALTER TABLE Programa_Academico ADD CONSTRAINT chk_nivel_estudio CHECK (Nivel_Estudio IN ('Pregrado', 'Posgrado', 'Técnico', 'Tecnólogo'));
ALTER TABLE Estudiante ADD CONSTRAINT chk_semestre CHECK (Semestre > 0);
ALTER TABLE Asignatura ADD CONSTRAINT chk_creditos CHECK (Creditos > 0);
ALTER TABLE Proyecto ADD CONSTRAINT chk_tipo_proyecto CHECK (Tipo IN ('PA', 'PIA'));
ALTER TABLE Proyecto ADD CONSTRAINT chk_estado_proyecto CHECK (Estado IN ('Borrador', 'Activo', 'Finalizado', 'Cancelado'));
ALTER TABLE Proyecto ADD CONSTRAINT chk_fechas_proyecto CHECK (Fecha_Fin > Fecha_Inicio);
ALTER TABLE Entregable ADD CONSTRAINT chk_estado_entregable CHECK (Estado IN ('Pendiente', 'Entregado', 'Aprobado', 'Rechazado'));
ALTER TABLE Criterio_Rubrica ADD CONSTRAINT chk_ponderacion CHECK (Ponderacion > 0 AND Ponderacion <= 100);
ALTER TABLE Evaluacion ADD CONSTRAINT chk_tipo_evaluacion CHECK (Tipo_Evaluacion IN ('Autoevaluación', 'Coevaluación', 'Heteroevaluación'));
ALTER TABLE Resultado_Evaluacion ADD CONSTRAINT chk_calificacion CHECK (Calificacion >= 0 AND Calificacion <= 5.0);
ALTER TABLE Calendario_Entrega ADD CONSTRAINT chk_tipo_evento CHECK (Tipo_Evento IN ('Entrega', 'Revisión', 'Sesión', 'Presentación'));
ALTER TABLE Calendario_Entrega ADD CONSTRAINT chk_fechas_calendario CHECK (Fecha_Hora_Fin > Fecha_Hora_Inicio);
ALTER TABLE Requerimiento_Insumo ADD CONSTRAINT chk_cantidad CHECK (Cantidad > 0);
ALTER TABLE Requerimiento_Insumo ADD CONSTRAINT chk_estado_requerimiento CHECK (Estado IN ('Solicitado', 'Aprobado', 'Rechazado', 'Entregado'));
ALTER TABLE Notificacion ADD CONSTRAINT chk_tipo_notificacion CHECK (Tipo IN ('Sistema', 'Mensaje', 'Alerta', 'Recordatorio'));
ALTER TABLE Historial_Cambio ADD CONSTRAINT chk_accion CHECK (Accion IN ('INSERT', 'UPDATE', 'DELETE'));

-- DEFAULT Values
ALTER TABLE Usuario ALTER COLUMN Activo SET DEFAULT TRUE;
ALTER TABLE Usuario ALTER COLUMN Fecha_Registro SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE Microcurriculo ALTER COLUMN Fecha_Actualizacion SET DEFAULT CURRENT_DATE;
ALTER TABLE Rubrica_Evaluacion ALTER COLUMN Fecha_Creacion SET DEFAULT CURRENT_DATE;
ALTER TABLE Requerimiento_Insumo ALTER COLUMN Fecha_Solicitud SET DEFAULT CURRENT_DATE;
ALTER TABLE Notificacion ALTER COLUMN Fecha_Envio SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE Notificacion ALTER COLUMN Leida SET DEFAULT FALSE;
ALTER TABLE Historial_Cambio ALTER COLUMN Fecha_Cambio SET DEFAULT CURRENT_TIMESTAMP;